services:
  nginx:
    image: nginx:alpine
    container_name: nebula-proxy
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs/npm:/var/log/nginx:rw
    networks:
      - nebula-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nebula-pulse:
    build: ./pulse
    container_name: nebula-pulse
    restart: unless-stopped
    ports:
      - '2019:2019'
    volumes:
      - /proc:/proc:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - nebula-network

  static-web:
    image: nginx:alpine
    container_name: nebula-static
    restart: unless-stopped
    volumes:
      - ./apps/static-web/html:/usr/share/nginx/html:ro
      - ./logs/static:/var/log/nginx:rw
    networks:
      - nebula-network

networks:
  nebula-network:
    external: true
